### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haskell#946]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/haskell/issues/937)
- [ ] [Add key features](https://github.com/exercism/haskell/issues/938)
- [ ] [Add tags](https://github.com/exercism/haskell/issues/939)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/haskell/issues/940)
- [ ] [Update status of track](https://github.com/exercism/haskell/issues/944)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/haskell/issues/945)
- [ ] [Pass linting checks](https://github.com/exercism/haskell/issues/941)
- [ ] [Build Test Runner](https://github.com/exercism/haskell/issues/942)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/haskell/issues/943) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
